package com.example.countriesapp.framework.local

object CapitalProvider {

    fun getCapitals():ArrayList<String>{
        return capitalList
    }


    private val capitalList: ArrayList<String> = arrayListOf(
        "Kabul",
        "Tirana",
        "Berlín",
        "Luanda",
        "Saint John's",
        "Riad",
        "Argel",
        "Buenos Aires",
        "Ereván",
        "Camberra",
        "Viena",
        "Bakú",
        "Nasáu",
        "Daca",
        "Bridgetown",
        "Manama",
        "Bruselas",
        "Belmopán",
        "Porto Novo y Cotonú",
        "Minsk",
        "Naipyido",
        "Sucre",
        "Sarajevo",
        "Gaborone",
        "Brasilia",
        "Bandar Seri Begawan",
        "Sofía",
        "Uagadugú",
        "Guitega",
        "Praia",
        "Nom Pen",
        "Yaundé",
        "Ottawa",
        "Doha",
        "Yamena",
        "Santiago de Chile",
        "Pekín",
        "Nicosia",
        "Ciudad del Vaticano",
        "Bogotá",
        "Moroni",
        "Pionyang",
        "Seul",
        "Yamusukro",
        "San José",
        "Zagreb",
        "La Habana",
        "Copenhague",
        "Roseau",
        "Quito",
        "El Cairo",
        "San Salvador",
        "Abu Dabi",
        "Asmara",
        "Bratislava",
        "Liubliana",
        "Madrid",
        "Washington, D.C.",
        "Tallin",
        "Adís Abeba",
        "Manila",
        "Helsinki",
        "Suva",
        "París",
        "Libreville",
        "Banjul",
        "Tiflis",
        "Acra",
        "Saint George",
        "Atenas",
        "Ciudad de Guatemala",
        "Georgetown",
        "Conakri",
        "Bisau",
        "Malabo",
        "Budapest",
        "Nueva Delhi",
        "Yakarta",
        "Bagdad",
        "Teherán",
        "Dublín",
        "Reikiavik",
        "Majuro",
        "Honiara",
        "Jerusalén",
        "Roma",
        "Kingston",
        "Tokio",
        "Amán",
        "Nursultán",
        "Nairobi",
        "Biskek",
        "Tarawa",
        "Kuwait",
        "Vientián",
        "Maseru",
        "Riga",
        "Beirut",
        "Monrovia",
        "Trípoli",
        "Vaduz",
        "Vilna",
        "Luxemburgo",
        "Skopie",
        "Antananarivo",
        "Kuala Lumpur",
        "Lilongüe",
        "Malé",
        "Bamako",
        "La Valeta",
        "Rabat",
        "Port-Louis",
        "Nuakchot",
        "Ciudad de México",
        "Palikir",
        "Chisináu",
        "Monaco",
        "Ulán Bator",
        "Podgorica",
        "Maputo",
        "Windhoek",
        "Yaren",
        "Katmandú",
        "Managua",
        "Niamey",
        "Abuya",
        "Oslo",
        "Wellington",
        "Mascate",
        "Ámsterdam",
        "Islamabad",
        "Melekeok",
        "Panamá",
        "Port Moresby",
        "Asunción",
        "Lima",
        "Varsovia",
        "Lisboa",
        "Londres",
        "Bangui",
        "Praga",
        "Brazzaville",
        "Kinsasa",
        "Santo Domingo",
        "Pretoria",
        "Kigali",
        "Bucarest",
        "Moscú",
        "Apia",
        "Basseterre",
        "San Marino",
        "Kingstown",
        "Castries",
        "Santo Tomé",
        "Dakar",
        "Belgrado",
        "Victoria",
        "Freetown",
        "Singapur",
        "Damasco",
        "Mogadiscio",
        "Babane",
        "Jartum",
        "Yuba",
        "Estocolmo",
        "Berna",
        "Paramaribo",
        "Bangkok",
        "Dodoma",
        "Dusambé",
        "Dili",
        "Lomé",
        "Nukualofa",
        "Puerto España",
        "Túnez",
        "Asjabad",
        "Ankara",
        "Kiev",
        "Kampala",
        "Montevideo",
        "Taskent",
        "Port Vila",
        "Caracas",
        "Hanoi",
        "Sana",
        "Yibuti",
        "Lusaka",
        "Harare"
    )
}