package com.example.countriesapp.presentation.fragments.tabubication.current

import android.util.Log
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.countriesapp.framework.CountryViewModel
import com.example.countriesapp.framework.Interactors
import com.example.countriesapp.framework.local.room.CountryEntity
import com.example.countriesapp.presentation.models.UbicationClass
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

class ShowLocationViewModel(interactors: Interactors) : CountryViewModel(interactors){

    fun addCurrentLocation(entity: CountryEntity){

        viewModelScope.launch(Dispatchers.IO){
            interactors.saveCurrentLocationUseCase(entity)
        }
    }

    fun deleteSavedItem(date: String) {
        //Here i tried to send the id of the item I want to delete,
        // however the id is not autogenerated until the entity is inserted in the database, so i can't
        // know what is the id thats why Im using the date atribute.
        viewModelScope.launch(Dispatchers.IO){
            interactors.deleteSelectedLocationByDateUseCase(date)
        }
    }

}